apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.26
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Test1234!
        - name: MYSQL_DATABASE 
          value: btcweb
        - name: MYSQL_USER
          value: dana
        - name: MYSQL_PASSWORD
          value: Test1234!
        - name: MYSQL_ROOT_HOST
          value: '%'  
        ports:
        - containerPort: 3306