apiVersion: v1
kind: Service
metadata:
  name: service-mysql
spec:
  type: NodePort
  selector:
    app: btc-db-server
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30000
      targetPort: 3306