apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-was-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: btc-was-server
  template:
    metadata:
      labels:
        app: btc-was-server
    spec:
      containers:
        - name: btc-was-server
          image: pddana/btcwask8s:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: btc-was-service
spec:
  ports:
    - name: http-port
      port: 8081
      targetPort: 8081
  selector:
    app: btc-was-server
  type: LoadBalancer
